spring:
  cache:
    type: simple
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/aderi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
debug: true
logging:
  level:
    edu.jmu: debug