spring:
  cache:
    type: simple
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oscm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
debug: true
logging:
  level:
    edu.jmu: debug