spring:
  cache:
    type: simple
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aderi?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
debug: true
logging:
  level:
    edu.jmu: debug