spring:
  profiles:
    active: dev
jwt:
  header: Authorization
  secret: mySecret
  expiration: 3600000
  route:
    authentication:
      path: /auth
      refresh: /refresh
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml,security/mapper/*Mapper.xml